<Project>
  <PropertyGroup>
    <ValheimPath Condition="'$(ValheimPath)' == ''">D:\SteamLibrary\steamapps\common\Valheim</ValheimPath>
    <ValheimManaged>$(ValheimPath)\valheim_Data\Managed</ValheimManaged>
    <BepInExPath Condition="'$(BepInExPath)' == ''">C:\Users\cdjen\AppData\Roaming\r2modmanPlus-local\Valheim\profiles\Default\BepInEx</BepInExPath>
    <BepInExCore>$(BepInExPath)\core</BepInExCore>
  </PropertyGroup>
</Project>
